name: cached_video_player
description: A new flutter plugin that is virtually a clone of official video_player plugin except that it supports caching( Android and iOS)
version: 2.0.0-dev.1
homepage: https://github.com/vikram25897/flutter_cached_video_player

flutter:
  plugin:
    platforms:
      android:
        package: com.lazyarts.vikram.cached_video_player
        pluginClass: CVideoPlayerPlugin
      ios:
        pluginClass: FLTCVideoPlayerPlugin
      web:
        default_package: video_player_web

dependencies:
  meta: ^1.7.0
  video_player_platform_interface: ^4.1.0

  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint. The exact value doesn't matter since
  # the constraints on the interface pins it.
  # TODO(amirh): Revisit this (either update this part in the design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  video_player_web: ^2.0.2

  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.1
  pigeon: ^0.1.24

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
